### ISSUE TITLE
Плагин не работает в последнем PHPStorm

### ISSUE THREAD

**Issue by don-tre** [VKCOM/modulite#20]
Здравствуйте! 
Отличный и крайне необходимый плагин!

у меня PHPStrom 2023.1.1

Планируется ли адаптация плагина под эту версию?

<img width="167" alt="modulite_latest_issue" src="https://github.com/VKCOM/modulite/assets/5460215/0590800f-beea-45ae-8e6a-9a498136b98d">

**Comment by Hidanio** [comment]
@don-tre, Доброго времени суток!
Данный плагин адаптирован со всеми версиями PhpStorm (включая и последнюю).
Пробовали ли вы обновляться до последней версии?
Обращаю ваше внимание что JetBrains больше не может предоставлять услуги VK как компании из РФ, поэтому все наши плагины распространяются не через официальный Marketplace, а через наш собственный.
Ссылка на документацию по установке и обновлению : 
https://vkcom.github.io/modulite/install.html
Буду рад ответить на ваши вопросы, если они имеются.
