### ISSUE TITLE
PhpStorm 223.* compatibility

### ISSUE THREAD

**Issue by SerafimArts** [VKCOM/modulite#3]
Plugin currently not compatible with PhpStorm 2022.3 RC (223.*)

![image](https://user-images.githubusercontent.com/2461257/204112593-d39db588-68fc-420b-b844-f904bfac8fc0.png)
![image](https://user-images.githubusercontent.com/2461257/204112626-ef0b2730-bc3a-4aea-88c9-8a100cfaccc7.png)

**Comment by githubjeka** [comment]
Link to succeed assembly `modulite-1.1.0.jar` for PhpStorm 223.* `deleted`
Decryption key `deleted`

Comment from the developer:
> I deleted the link, due to the lack of security guarantees. Please download the plugin from the [official](https://github.com/VKCOM/modulite/releases/tag/v1.1.1) release.

**Comment by SerafimArts** [comment]
🥳
