### ISSUE TITLE
Enlarge symbol selection widget

### ISSUE THREAD

**Issue by Chi-teck** [VKCOM/modulite#33]
Currently it looks like follows.
![Screenshot_20231031_211837](https://github.com/VKCOM/modulite/assets/673139/01a7ba35-a01f-4d8e-ba34-e56345832f21)

It's hard to pick items in such a small window.

**Comment by Hidanio** [comment]
Hello, @Chi-teck . Thank you for your suggestion. It will be implemented in the next update.
