### ISSUE TITLE
Plugin is not available in marketplace

### ISSUE THREAD

**Issue by Ragaga** [VKCOM/modulite#45]
Custom plugin repository has been added, but plugin is not appear in list
https://idea-plugins.kphp.dev/ responded empty plugins tag

**Comment by nokimaro** [comment]
@Hidanio can you please check this issue? Can't install plugin from custom repository idea-plugins.kphp.dev

**Comment by Hidanio** [comment]
> @Hidanio can you please check this issue? Can't install plugin from custom repository idea-plugins.kphp.dev

I'm already looking into the issue. I'll be back in a couple of days.

**Comment by Hidanio** [comment]
@nokimaro @Ragaga Hello! Everything should be ok now.

**Comment by Ragaga** [comment]
@Hidanio It's not available again :'( 2024.2

**Comment by Hidanio** [comment]
@Ragaga we have not support for 2024.2 now :(
Only 2024.1
Currently focused on fixing functionality and generating dependencies

**Comment by des1roer** [comment]
![image](https://github.com/user-attachments/assets/6628ed6c-2148-45dc-aa91-ad6a96512cbd)

**Comment by Hidanio** [comment]
> ![image](https://private-user-images.githubusercontent.com/10970793/364760945-6628ed6c-2148-45dc-aa91-ad6a96512cbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzY4NzgsIm5iZiI6MTcyNTUzNjU3OCwicGF0aCI6Ii8xMDk3MDc5My8zNjQ3NjA5NDUtNjYyOGVkNmMtMjE0OC00NWRjLWFhOTEtYWQ2YTk2NTEyY2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDExNDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YWUyODRmMzU0MDMwOWRjM2VlNGVkNmVkMjM3MGNiYjM5NWEzNWVjMGZiMzg2MzZmNzZiYjhmYWExNzYyNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rrf4O-AKfXDr6CV5E9PIbyK1ktaJYsujpf2Oq9UZlEc)

IDE version?

**Comment by des1roer** [comment]
сори, не увидел что нужно через прокси подключать
