### ISSUE TITLE
Не удается установить

### ISSUE THREAD

**Issue by des1roer** [VKCOM/modulite#54]
![image](https://github.com/user-attachments/assets/7cded98f-a93c-4bdd-80a4-96a2eb872aa7)

**Comment by Hidanio** [comment]
> ![image](https://private-user-images.githubusercontent.com/10970793/364759616-7cded98f-a93c-4bdd-80a4-96a2eb872aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTgwNDIsIm5iZiI6MTcyNTU1Nzc0MiwicGF0aCI6Ii8xMDk3MDc5My8zNjQ3NTk2MTYtN2NkZWQ5OGYtYTkzYy00YmRkLTgwYTQtOTZhMmViODcyYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE3MzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YzllYzEyZWM0ODQyNTVmZTFiYWNjMTRkNjU5YmFjMTFkOWIyNmIxMDQ2YjdhOTUwYmFlYjRjYjAzNWZjODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tB6naU9cNVksePBgUBGLtLUDGvE0_JLKW9uL0-n4eQw)

IDE version?

**Comment by PatchRanger** [comment]
Подтверждаю наличие проблемы: не работает в версии PHPStorm свежее 223.
Удаётся прописать репозиторий (как описано в инструкции https://vkcom.github.io/modulite/install.html ) - но плагин не находится даже после рестарта IDE, полагаю из-за несовместимости версий.

Попробовал установить вручную, из файла:
1) Скачать zip отсюда https://github.com/VKCOM/modulite/releases/tag/v1.1.1 .
2) Вытащить оттуда jar-файл.
3) В PHPStorm выбрать его после нажатия Install from Disk... в меню плагинов.

Выдаёт вот такую ошибку: 

![Image](https://github.com/user-attachments/assets/75e170ec-e336-4ca9-8f4e-608cfc99cf8d)

У меня вот такая версия PHPStorm: 2024.3.3, Build #PS-243.24978.50, built on February 12, 2025.

Прошу бампнуть поддерживаемую версию PHPStorm, чтобы использовать этот замечательный плагин в новых версиях IDE.

Я вижу, что в ветке master уже проделана какая-то работа по поддержке версий, спасибо!) Буду ждать поддержки версии 2024.3.3 (243).

**Comment by Hidanio** [comment]
@PatchRanger вскоре будет поддержка 2024.3.1
